### ISSUE TITLE
Criar estrutura básica para desenvolvimento

### ISSUE THREAD

**Issue by chronossc** [TaturanaMobi/ops#1]
Estou colocando requerimentos para montarmos uma estrutura básica pro desenvolvimento com docker.

Já fiz alguma coisa no repo do plataforma-v2 mas nada realmente descente que agilize muito, e eu não manjo mto de docker.

Vou precisar das seguintes coisas rodando a priore:

* Base: Ubuntu Server 18.04 LTS, com python 3.6 
* DB: Postgresql 10x
* Cache: Redis 4.x
* Broker: Rabbitmq 3.7.x

Estou subindo um app assim:

```
PROJECT_BASE_FOLDER='/opt/taturana-v2/'
PREFIX='taturana-v2'
up='docker run -itd --restart always'

$up --name ${PREFIX}-app \
  --volume $PROJECT_BASE_FOLDER:/opt/taturana-v2 \
  --entrypoint /bin/bash \
  ubuntu:18.04 

docker exec -ti ${PREFIX}-app bash -c 'apt update'
docker exec -ti ${PREFIX}-app bash -c 'apt install python3 python3-pip vim -y'  # isso instala mais de 300MB de coisas :\
docker exec -ti ${PREFIX}-app bash -c 'ln -s /usr/bin/python3 /usr/bin/python'
```
(mais detalhes em https://github.com/TaturanaMobi/plataforma-v2/commit/c70408b417b7355ad52e2aff1a888ff2ab489e0c)

O volume do banco não preciso acessar diretamente, mas o volume do código sim :).
Preciso que o container do app possa acessar todos os outros tbm.

**Comment by lpirola** [comment]
@chronossc vou resolver essa issue nesse PR https://github.com/TaturanaMobi/plataforma-frontend/pull/1

**Comment by lpirola** [comment]
@chronossc criei a estrutura básica nesse PR https://github.com/TaturanaMobi/plataforma-v2/pull/2 me avisa se está tudo como você gostaria.

Provavelmente, no futuro, tudo estará em apenas um arquivo docker-compose.yml, enquanto isso não acontece, vou manter um para cada repositório.

Se entender que existe algum problema, em avisa.
